
- name: Configurar Switch Este
  hosts: sw-este
  gather_facts: false
  connection: local
  
  tasks:
  - name: show vlan
    ios_command:
      authorize: yes
      commands:
        - show vlan brief
    register: sh_vlan

  - debug: var=sh_vlan.stdout_lines
